mir-json-up: Further corrections to the 'list' command to handle the case of the toolchains directory not existing.

diff --git a/mir-json-up/mir-json-up b/mir-json-up/mir-json-up
--- a/mir-json-up/mir-json-up
+++ b/mir-json-up/mir-json-up
@@ -221,11 +221,11 @@ check_general_prerequisites() {
        if [[ $INITIALIZE_IF_MISSING == 0 ]]; then
             echo "Checking out source repository for mir-json ${MIR_JSON_VERSION}" 1>&2
             get_mir_json_src "${MIR_JSON_VERSION}"
+            if [[ ! -d "$(get_mir_json_src_dir ${MIR_JSON_VERSION})" ]]; then
+                echo "mir-json ${MIR_JSON_VERSION} failed to check out" 1>&2
+                exit 1
+            fi
        fi
-        if [[ ! -d "$(get_mir_json_src_dir ${MIR_JSON_VERSION})" ]]; then
-            echo "mir-json ${MIR_JSON_VERSION} failed to check out" 1>&2
-            exit 1
-        fi
     else
         if [[ ! -d "$(get_mir_json_src_dir ${MIR_JSON_VERSION})" ]]; then
             echo "mir-json ${MIR_JSON_VERSION} not checked out" 1>&2
@@ -398,8 +398,11 @@ case "$COMMAND" in
             echo "${MIR_JSON_INSTALL_DIR} does not exist" 1>&2
             exit 1
         fi
+        if [[ ! -d "${MIR_JSON_INSTALL_DIR}/toolchains" || -z $(ls -A "${MIR_JSON_INSTALL_DIR}/toolchains") ]]; then
+            exit 0
+        fi
         cd "${MIR_JSON_INSTALL_DIR}/toolchains"
-        for toolchain in $(ls -1d */*/* | grep -v "[*]/[*]/[*]"); do
+        for toolchain in $(ls -1d */*/*); do
             echo -n "$toolchain"
             if [[ -f "${MIR_JSON_INSTALL_DIR}/default/id" ]]; then
                 ACTIVE_TOOLCHAIN=$(cat "${MIR_JSON_INSTALL_DIR}/default/id")
